#####################################################################################
# Copyright (c) 2022-present, Advanced Micro Devices, Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#####################################################################################

from typing import Dict, List, Optional, Sequence, Tuple
import copy
import logging
import os

import torch
from torch.fx.passes.shape_prop import ShapeProp
import migraphx

from torch_migraphx.fx.mgx_module import MGXModule
from torch_migraphx.fx.fx2mgx import MGXInterpreter
from torch_migraphx.fx.passes.pass_utils import validate_inference

from .mutation import graph_has_side_effects, graph_may_mutate
from .passes.pass_manager import pre_partition_pass, post_partition_pass, post_lowering_pass
from .passes.partition import partition
from .passes.rewrite_output_aliases import (
    apply_alias_rewrite,
    capture_partition_io,
    plan_alias_rewrite,
)
from .utils import get_input_info, get_graph_info, SetLogLevel

_LOGGER = logging.getLogger(__name__)
DYNAMO_LOGLEVEL = os.environ.get('TORCH_MIGRAPHX_LOG_DYNAMO_LOWER', None)
if DYNAMO_LOGLEVEL:
    _LOGGER.setLevel(DYNAMO_LOGLEVEL)


def lower_aten_to_mgx(gm: torch.fx.GraphModule,
                      example_inputs: Sequence[torch.Tensor],
                      **kwargs) -> torch.fx.GraphModule:
    """Lower aten GraphModule generated by dynamo and AOT Autograd to MIGraphX.
       1) Partition the graph into supported and unsupported subgraphs
       2) Lower to each supported subgraph to MIGraphX
       3) Replace original GraphModules with lowered MGXModules

    Args:
        gm (torch.fx.GraphModule): Graph generated by dynamo and aot autograd
        example_inputs (Sequence[torch.Tensor]): Example inputs

    Returns:
        torch.fx.GraphModule: GraphModule contatning MGXModule objects for supported subgraphs
    """
    verbose = kwargs.get("verbose", False)
    if verbose and _LOGGER.level == logging.NOTSET: 
        _LOGGER.setLevel(logging.INFO)

    optim_gm = pre_partition_pass(gm)
    partition(optim_gm, verbose=verbose)

    # Capturing a partition's inputs runs the whole graph, so every capture
    # needs pristine values when the graph writes to them.
    capture_inputs = (copy.deepcopy(example_inputs)
                      if graph_may_mutate(optim_gm) else example_inputs)

    log_level = min(_LOGGER.level, logging.INFO) if verbose else _LOGGER.level
    with SetLogLevel(_LOGGER, log_level):
        for name, call_node in _partition_calls(optim_gm).items():
            _lower_partition(optim_gm, name, call_node, capture_inputs,
                             **kwargs)

        lowered_gm = post_lowering_pass(optim_gm)
        lowered_gm._tracer_cls = None
        return lowered_gm


def _partition_calls(
        gm: torch.fx.GraphModule) -> Dict[str, Optional[torch.fx.Node]]:
    """Fused partitions of a graph, in the order they are executed.

    Capturing partition inputs runs the partially lowered graph, so consumers
    have to be lowered after their producers to observe the layouts those
    producers actually give them.

    The node calling a partition is needed to rewrite its call site. A
    partition called from more than one site maps to None, since rewriting one
    call site would leave the others reading the old outputs.
    """
    calls: Dict[str, Optional[torch.fx.Node]] = {}
    for node in gm.graph.nodes:
        if node.op != "call_module" or not isinstance(
                gm.get_submodule(node.target), torch.fx.GraphModule):
            continue
        calls[node.target] = None if node.target in calls else node
    return calls


def _lower_partition(gm: torch.fx.GraphModule, name: str,
                     call_node: Optional[torch.fx.Node],
                     example_inputs: Sequence[torch.Tensor], **kwargs):
    """Replace one fused partition with a compiled MIGraphX module.

    Partitions that cannot be expressed as a MIGraphX program are left in
    PyTorch, which costs performance but keeps the graph correct.
    """
    submodule = post_partition_pass(gm.get_submodule(name))
    if graph_has_side_effects(submodule):
        _LOGGER.warning(f"Leaving subgraph {name} in PyTorch because it has "
                        "side effects MIGraphX cannot reproduce")
        return

    capture = capture_partition_io(gm, submodule, example_inputs)
    if not capture.aliases_representable:
        _LOGGER.warning(f"Leaving subgraph {name} in PyTorch because its "
                        "output aliases cannot be represented safely")
        return

    # Aliased outputs are rebuilt as views at the call site instead of being
    # returned by the compiled partition, which cannot alias anything.
    rewrite = None
    if capture.aliases:
        if call_node is None:
            _LOGGER.warning(f"Leaving subgraph {name} in PyTorch because it "
                            "aliases outputs and is called more than once")
            return

        rewrite = plan_alias_rewrite(submodule, capture.aliases)
        submodule = rewrite.module
        if rewrite.prunes_every_output:
            apply_alias_rewrite(gm, call_node, rewrite)
            return

    _LOGGER.info(f"Lowering subgraph: {name}")
    _LOGGER.info(f"Subgraph inputs: {get_input_info(capture.inputs)}")
    _LOGGER.info(f"Subgraph:\n{get_graph_info(submodule.graph)}")

    mgx_module = lower_subgraph(submodule,
                                capture.inputs,
                                name=name,
                                **kwargs)

    if rewrite is not None:
        if not rewrite.supports_output_layouts(_output_layouts(mgx_module)):
            _LOGGER.warning(f"Leaving subgraph {name} in PyTorch because "
                            "MIGraphX changed an output layout an alias is "
                            "rebuilt from")
            return
        apply_alias_rewrite(gm, call_node, rewrite)

    setattr(gm, name, mgx_module)


def _output_layouts(
        mgx_module: MGXModule) -> List[Tuple[Sequence[int], Sequence[int]]]:
    return [(shape.lens(), shape.strides())
            for shape in mgx_module.output_mgx_shapes]



# @validate_inference(0.1, 0.1)
def lower_subgraph(module: torch.fx.GraphModule,
                   inputs: Sequence[torch.Tensor], **kwargs) -> MGXModule:
    """Lower graph to migraphx module. This graph should only contain supported nodes.

    Args:
        module (torch.fx.GraphModule): Graph to compile in MIGraphX
        inputs (Sequence[torch.Tensor]): Example inputs to the graph

    Returns:
        MGXModule: Callable module that executes graph via MIGraphX
    """

    fp16 = kwargs['fp16'] if 'fp16' in kwargs else False
    bf16 = kwargs['bf16'] if 'bf16' in kwargs else False
    deallocate = kwargs['deallocate'] if 'deallocate' in kwargs else False
    exhaustive_tune = kwargs[
        'exhaustive_tune'] if 'exhaustive_tune' in kwargs else False
    save_mxr = kwargs['save_mxr'] if 'save_mxr' in kwargs else False

    interpreter = MGXInterpreter(module, inputs, deallocate=deallocate)
    interpreter.run()

    if save_mxr:
        prefix = f"{save_mxr}_" if isinstance(save_mxr, str) else ""
        name = f"{prefix}{kwargs['name']}.mxr" if 'name' in kwargs else f"{prefix}_prog.mxr"
        migraphx.save(interpreter.program, name)

    _LOGGER.debug(f"Interpreted Program:\n{interpreter.program}")

    mgx_module = MGXModule(program=interpreter.program,
                           input_names=interpreter.get_input_names(),
                           quantize_fp16=fp16,
                           quantize_bf16=bf16,
                           exhaustive_tune=exhaustive_tune)

    _LOGGER.debug(f"Compiled Program:\n{mgx_module.program}")

    return mgx_module
